"""update transacoes table

Revision ID: 1f0efc8ba29d
Revises: 612746d0f4c3
Create Date: 2025-12-07 16:47:31.523061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0efc8ba29d'
down_revision = '612746d0f4c3'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_original', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recorrente', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(
            'fk_transacoes_id_original',  # nome da constraint
            'transacoes',
            ['id_original'],
            ['id'],
            ondelete='SET NULL'
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recorrente')
        batch_op.drop_column('id_original')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
