"""account name add

Revision ID: 4613808f900a
Revises: 15d9c64ee406
Create Date: 2025-11-13 10:47:16.511692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4613808f900a'
down_revision = '15d9c64ee406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_conta', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.drop_column('nome_conta')

    # ### end Alembic commands ###
