"""Adiciona campo receita_ja_incluida a Transacoe

Revision ID: 4b7b689d0f5c
Revises: 16c4663e4a96
Create Date: 2025-12-11 18:45:48.404418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7b689d0f5c'
down_revision = '16c4663e4a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receita_ja_incluida', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.drop_column('receita_ja_incluida')

    # ### end Alembic commands ###
