"""Update all db

Revision ID: 612746d0f4c3
Revises: 85b18d5eec52
Create Date: 2025-11-30 12:49:21.481722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612746d0f4c3'
down_revision = '85b18d5eec52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyvalidation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_value', sa.String(length=100), nullable=False))
        batch_op.drop_column('Key')

    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('keyvalidation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Key', sa.INTEGER(), nullable=False))
        batch_op.drop_column('key_value')

    # ### end Alembic commands ###
