"""Datetime for Date

Revision ID: 85b18d5eec52
Revises: 4613808f900a
Create Date: 2025-11-30 00:06:32.361248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b18d5eec52'
down_revision = '4613808f900a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.alter_column('data_transacao',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.alter_column('data_transacao',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
