"""update transacao table

Revision ID: b5860cd54ac6
Revises: faf5ffe5ad18
Create Date: 2025-12-07 21:58:31.761093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5860cd54ac6'
down_revision = 'faf5ffe5ad18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcelas_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parcela_atual', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parcelado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.drop_column('parcelado')
        batch_op.drop_column('parcela_atual')
        batch_op.drop_column('parcelas_total')

    # ### end Alembic commands ###
